# nplex configuration file.
# see https://github.com/torrentg/nplex

addr = localhost:14022
log-level = info
max-clients = 128
disable-fsync = false

# number of entries/bytes before force a flush
# these values only applies if it cumulates more than x entries/bytes
;max-flush-entries = 50
;max-flush-bytes = 10MB

# entries pending to be committed
;max-uncommited-entries = 1024
;max-uncommited-bytes = 20MB

# criteria to create a snapshot considering the cumulated entries from previous snapshot
;max-snapshot-entries = 10000
;max-snapshot-bytes = 100MB

[defaults]
active = true
can-force = false
keepalive-millis = 1000
max-connections = 3

[admin]
password = s3cr3t
can-force = true
keepalive-millis = 250
max-connections = 10
acl = crud:**

[jdoe]
password = s3cr3t
acl = -r--:/sensors/**
acl = -ru-:/actuators/**
acl = cru-:/alarms/**
