# nplex configuration file.
# see https://github.com/torrentg/nplex

addr = localhost:14022
log-level = info
disable-fsync = false

max-clients = 256
write-queue-max-length = 1000
write-queue-max-bytes = 350MB
flush-max-entries = 50
flush-max-bytes = 25MB

[user-defaults]
active = true
can-force = false
max-connections = 3
# session default values
keepalive-millis = 1000
timeout-factor = 3.0
max-msg-bytes = 50MB
max-queue-length = 1000
max-queue-bytes = 350MB

[admin]
password = s3cr3t
can-force = true
keepalive-millis = 250
timeout-factor = 0.0
max-connections = 256
acl = crud:**

[jdoe]
password = s3cr3t
acl = -r--:/sensors/**
acl = -ru-:/actuators/**
acl = cru-:/alarms/**
