// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MESSAGES_NPLEX_MSGS_H_
#define FLATBUFFERS_GENERATED_MESSAGES_NPLEX_MSGS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

namespace nplex {
namespace msgs {

struct KeyValue;
struct KeyValueBuilder;

struct Update;
struct UpdateBuilder;

struct Snapshot;
struct SnapshotBuilder;

struct Acl;
struct AclBuilder;

struct LoginRequest;
struct LoginRequestBuilder;

struct LoginResponse;
struct LoginResponseBuilder;

struct PingRequest;
struct PingRequestBuilder;

struct PingResponse;
struct PingResponseBuilder;

struct LoadRequest;
struct LoadRequestBuilder;

struct LoadResponse;
struct LoadResponseBuilder;

struct ChangesPush;
struct ChangesPushBuilder;

struct SubmitRequest;
struct SubmitRequestBuilder;

struct SubmitResponse;
struct SubmitResponseBuilder;

struct KeepAlivePush;
struct KeepAlivePushBuilder;

struct Message;
struct MessageBuilder;

enum class LoginCode : int8_t {
  AUTHORIZED = 0,
  INVALID_CREDENTIALS = 1,
  TOO_MANY_CONNECTIONS = 2,
  UNSUPPORTED_API_VERSION = 3,
  MIN = AUTHORIZED,
  MAX = UNSUPPORTED_API_VERSION
};

inline const LoginCode (&EnumValuesLoginCode())[4] {
  static const LoginCode values[] = {
    LoginCode::AUTHORIZED,
    LoginCode::INVALID_CREDENTIALS,
    LoginCode::TOO_MANY_CONNECTIONS,
    LoginCode::UNSUPPORTED_API_VERSION
  };
  return values;
}

inline const char * const *EnumNamesLoginCode() {
  static const char * const names[5] = {
    "AUTHORIZED",
    "INVALID_CREDENTIALS",
    "TOO_MANY_CONNECTIONS",
    "UNSUPPORTED_API_VERSION",
    nullptr
  };
  return names;
}

inline const char *EnumNameLoginCode(LoginCode e) {
  if (::flatbuffers::IsOutRange(e, LoginCode::AUTHORIZED, LoginCode::UNSUPPORTED_API_VERSION)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesLoginCode()[index];
}

enum class SubmitCode : int8_t {
  ACCEPTED = 0,
  NO_MODIFICATIONS = 1,
  ERROR_INVALID_REVISION = 2,
  ERROR_INVALID_KEY = 3,
  ERROR_DUPLICATE_KEY = 4,
  ERROR_MESSAGE = 5,
  REJECTED_PERMISSION = 6,
  REJECTED_INTEGRITY = 7,
  REJECTED_ENSURE = 8,
  MIN = ACCEPTED,
  MAX = REJECTED_ENSURE
};

inline const SubmitCode (&EnumValuesSubmitCode())[9] {
  static const SubmitCode values[] = {
    SubmitCode::ACCEPTED,
    SubmitCode::NO_MODIFICATIONS,
    SubmitCode::ERROR_INVALID_REVISION,
    SubmitCode::ERROR_INVALID_KEY,
    SubmitCode::ERROR_DUPLICATE_KEY,
    SubmitCode::ERROR_MESSAGE,
    SubmitCode::REJECTED_PERMISSION,
    SubmitCode::REJECTED_INTEGRITY,
    SubmitCode::REJECTED_ENSURE
  };
  return values;
}

inline const char * const *EnumNamesSubmitCode() {
  static const char * const names[10] = {
    "ACCEPTED",
    "NO_MODIFICATIONS",
    "ERROR_INVALID_REVISION",
    "ERROR_INVALID_KEY",
    "ERROR_DUPLICATE_KEY",
    "ERROR_MESSAGE",
    "REJECTED_PERMISSION",
    "REJECTED_INTEGRITY",
    "REJECTED_ENSURE",
    nullptr
  };
  return names;
}

inline const char *EnumNameSubmitCode(SubmitCode e) {
  if (::flatbuffers::IsOutRange(e, SubmitCode::ACCEPTED, SubmitCode::REJECTED_ENSURE)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSubmitCode()[index];
}

enum class LoadMode : int8_t {
  SNAPSHOT_AT_LAST_REV = 0,
  SNAPSHOT_AT_FIXED_REV = 1,
  ONLY_UPDATES_FROM_REV = 2,
  MIN = SNAPSHOT_AT_LAST_REV,
  MAX = ONLY_UPDATES_FROM_REV
};

inline const LoadMode (&EnumValuesLoadMode())[3] {
  static const LoadMode values[] = {
    LoadMode::SNAPSHOT_AT_LAST_REV,
    LoadMode::SNAPSHOT_AT_FIXED_REV,
    LoadMode::ONLY_UPDATES_FROM_REV
  };
  return values;
}

inline const char * const *EnumNamesLoadMode() {
  static const char * const names[4] = {
    "SNAPSHOT_AT_LAST_REV",
    "SNAPSHOT_AT_FIXED_REV",
    "ONLY_UPDATES_FROM_REV",
    nullptr
  };
  return names;
}

inline const char *EnumNameLoadMode(LoadMode e) {
  if (::flatbuffers::IsOutRange(e, LoadMode::SNAPSHOT_AT_LAST_REV, LoadMode::ONLY_UPDATES_FROM_REV)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesLoadMode()[index];
}

enum class MsgContent : uint8_t {
  NONE = 0,
  PING_REQUEST = 1,
  PING_RESPONSE = 2,
  LOGIN_REQUEST = 3,
  LOGIN_RESPONSE = 4,
  LOAD_REQUEST = 5,
  LOAD_RESPONSE = 6,
  SUBMIT_REQUEST = 7,
  SUBMIT_RESPONSE = 8,
  CHANGES_PUSH = 9,
  KEEPALIVE_PUSH = 10,
  MIN = NONE,
  MAX = KEEPALIVE_PUSH
};

inline const MsgContent (&EnumValuesMsgContent())[11] {
  static const MsgContent values[] = {
    MsgContent::NONE,
    MsgContent::PING_REQUEST,
    MsgContent::PING_RESPONSE,
    MsgContent::LOGIN_REQUEST,
    MsgContent::LOGIN_RESPONSE,
    MsgContent::LOAD_REQUEST,
    MsgContent::LOAD_RESPONSE,
    MsgContent::SUBMIT_REQUEST,
    MsgContent::SUBMIT_RESPONSE,
    MsgContent::CHANGES_PUSH,
    MsgContent::KEEPALIVE_PUSH
  };
  return values;
}

inline const char * const *EnumNamesMsgContent() {
  static const char * const names[12] = {
    "NONE",
    "PING_REQUEST",
    "PING_RESPONSE",
    "LOGIN_REQUEST",
    "LOGIN_RESPONSE",
    "LOAD_REQUEST",
    "LOAD_RESPONSE",
    "SUBMIT_REQUEST",
    "SUBMIT_RESPONSE",
    "CHANGES_PUSH",
    "KEEPALIVE_PUSH",
    nullptr
  };
  return names;
}

inline const char *EnumNameMsgContent(MsgContent e) {
  if (::flatbuffers::IsOutRange(e, MsgContent::NONE, MsgContent::KEEPALIVE_PUSH)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMsgContent()[index];
}

template<typename T> struct MsgContentTraits {
  static const MsgContent enum_value = MsgContent::NONE;
};

template<> struct MsgContentTraits<nplex::msgs::PingRequest> {
  static const MsgContent enum_value = MsgContent::PING_REQUEST;
};

template<> struct MsgContentTraits<nplex::msgs::PingResponse> {
  static const MsgContent enum_value = MsgContent::PING_RESPONSE;
};

template<> struct MsgContentTraits<nplex::msgs::LoginRequest> {
  static const MsgContent enum_value = MsgContent::LOGIN_REQUEST;
};

template<> struct MsgContentTraits<nplex::msgs::LoginResponse> {
  static const MsgContent enum_value = MsgContent::LOGIN_RESPONSE;
};

template<> struct MsgContentTraits<nplex::msgs::LoadRequest> {
  static const MsgContent enum_value = MsgContent::LOAD_REQUEST;
};

template<> struct MsgContentTraits<nplex::msgs::LoadResponse> {
  static const MsgContent enum_value = MsgContent::LOAD_RESPONSE;
};

template<> struct MsgContentTraits<nplex::msgs::SubmitRequest> {
  static const MsgContent enum_value = MsgContent::SUBMIT_REQUEST;
};

template<> struct MsgContentTraits<nplex::msgs::SubmitResponse> {
  static const MsgContent enum_value = MsgContent::SUBMIT_RESPONSE;
};

template<> struct MsgContentTraits<nplex::msgs::ChangesPush> {
  static const MsgContent enum_value = MsgContent::CHANGES_PUSH;
};

template<> struct MsgContentTraits<nplex::msgs::KeepAlivePush> {
  static const MsgContent enum_value = MsgContent::KEEPALIVE_PUSH;
};

bool VerifyMsgContent(::flatbuffers::Verifier &verifier, const void *obj, MsgContent type);
bool VerifyMsgContentVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<MsgContent> *types);

struct KeyValue FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef KeyValueBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KEY = 4,
    VT_VALUE = 6
  };
  const ::flatbuffers::String *key() const {
    return GetPointer<const ::flatbuffers::String *>(VT_KEY);
  }
  const ::flatbuffers::Vector<uint8_t> *value() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_VALUE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_KEY) &&
           verifier.VerifyString(key()) &&
           VerifyOffsetRequired(verifier, VT_VALUE) &&
           verifier.VerifyVector(value()) &&
           verifier.EndTable();
  }
};

struct KeyValueBuilder {
  typedef KeyValue Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_key(::flatbuffers::Offset<::flatbuffers::String> key) {
    fbb_.AddOffset(KeyValue::VT_KEY, key);
  }
  void add_value(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> value) {
    fbb_.AddOffset(KeyValue::VT_VALUE, value);
  }
  explicit KeyValueBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<KeyValue> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<KeyValue>(end);
    fbb_.Required(o, KeyValue::VT_KEY);
    fbb_.Required(o, KeyValue::VT_VALUE);
    return o;
  }
};

inline ::flatbuffers::Offset<KeyValue> CreateKeyValue(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> key = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> value = 0) {
  KeyValueBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_key(key);
  return builder_.Finish();
}

struct KeyValue::Traits {
  using type = KeyValue;
  static auto constexpr Create = CreateKeyValue;
};

inline ::flatbuffers::Offset<KeyValue> CreateKeyValueDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *key = nullptr,
    const std::vector<uint8_t> *value = nullptr) {
  auto key__ = key ? _fbb.CreateString(key) : 0;
  auto value__ = value ? _fbb.CreateVector<uint8_t>(*value) : 0;
  return nplex::msgs::CreateKeyValue(
      _fbb,
      key__,
      value__);
}

struct Update FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UpdateBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_REV = 4,
    VT_USER = 6,
    VT_TIMESTAMP = 8,
    VT_TYPE = 10,
    VT_UPSERTS = 12,
    VT_DELETES = 14
  };
  uint64_t rev() const {
    return GetField<uint64_t>(VT_REV, 0);
  }
  const ::flatbuffers::String *user() const {
    return GetPointer<const ::flatbuffers::String *>(VT_USER);
  }
  uint64_t timestamp() const {
    return GetField<uint64_t>(VT_TIMESTAMP, 0);
  }
  uint32_t type() const {
    return GetField<uint32_t>(VT_TYPE, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<nplex::msgs::KeyValue>> *upserts() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<nplex::msgs::KeyValue>> *>(VT_UPSERTS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *deletes() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_DELETES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_REV, 8) &&
           VerifyOffsetRequired(verifier, VT_USER) &&
           verifier.VerifyString(user()) &&
           VerifyField<uint64_t>(verifier, VT_TIMESTAMP, 8) &&
           VerifyField<uint32_t>(verifier, VT_TYPE, 4) &&
           VerifyOffset(verifier, VT_UPSERTS) &&
           verifier.VerifyVector(upserts()) &&
           verifier.VerifyVectorOfTables(upserts()) &&
           VerifyOffset(verifier, VT_DELETES) &&
           verifier.VerifyVector(deletes()) &&
           verifier.VerifyVectorOfStrings(deletes()) &&
           verifier.EndTable();
  }
};

struct UpdateBuilder {
  typedef Update Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_rev(uint64_t rev) {
    fbb_.AddElement<uint64_t>(Update::VT_REV, rev, 0);
  }
  void add_user(::flatbuffers::Offset<::flatbuffers::String> user) {
    fbb_.AddOffset(Update::VT_USER, user);
  }
  void add_timestamp(uint64_t timestamp) {
    fbb_.AddElement<uint64_t>(Update::VT_TIMESTAMP, timestamp, 0);
  }
  void add_type(uint32_t type) {
    fbb_.AddElement<uint32_t>(Update::VT_TYPE, type, 0);
  }
  void add_upserts(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<nplex::msgs::KeyValue>>> upserts) {
    fbb_.AddOffset(Update::VT_UPSERTS, upserts);
  }
  void add_deletes(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> deletes) {
    fbb_.AddOffset(Update::VT_DELETES, deletes);
  }
  explicit UpdateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Update> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Update>(end);
    fbb_.Required(o, Update::VT_USER);
    return o;
  }
};

inline ::flatbuffers::Offset<Update> CreateUpdate(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t rev = 0,
    ::flatbuffers::Offset<::flatbuffers::String> user = 0,
    uint64_t timestamp = 0,
    uint32_t type = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<nplex::msgs::KeyValue>>> upserts = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> deletes = 0) {
  UpdateBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_rev(rev);
  builder_.add_deletes(deletes);
  builder_.add_upserts(upserts);
  builder_.add_type(type);
  builder_.add_user(user);
  return builder_.Finish();
}

struct Update::Traits {
  using type = Update;
  static auto constexpr Create = CreateUpdate;
};

inline ::flatbuffers::Offset<Update> CreateUpdateDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t rev = 0,
    const char *user = nullptr,
    uint64_t timestamp = 0,
    uint32_t type = 0,
    const std::vector<::flatbuffers::Offset<nplex::msgs::KeyValue>> *upserts = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *deletes = nullptr) {
  auto user__ = user ? _fbb.CreateString(user) : 0;
  auto upserts__ = upserts ? _fbb.CreateVector<::flatbuffers::Offset<nplex::msgs::KeyValue>>(*upserts) : 0;
  auto deletes__ = deletes ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*deletes) : 0;
  return nplex::msgs::CreateUpdate(
      _fbb,
      rev,
      user__,
      timestamp,
      type,
      upserts__,
      deletes__);
}

struct Snapshot FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SnapshotBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_REV = 4,
    VT_UPDATES = 6
  };
  uint64_t rev() const {
    return GetField<uint64_t>(VT_REV, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<nplex::msgs::Update>> *updates() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<nplex::msgs::Update>> *>(VT_UPDATES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_REV, 8) &&
           VerifyOffset(verifier, VT_UPDATES) &&
           verifier.VerifyVector(updates()) &&
           verifier.VerifyVectorOfTables(updates()) &&
           verifier.EndTable();
  }
};

struct SnapshotBuilder {
  typedef Snapshot Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_rev(uint64_t rev) {
    fbb_.AddElement<uint64_t>(Snapshot::VT_REV, rev, 0);
  }
  void add_updates(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<nplex::msgs::Update>>> updates) {
    fbb_.AddOffset(Snapshot::VT_UPDATES, updates);
  }
  explicit SnapshotBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Snapshot> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Snapshot>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Snapshot> CreateSnapshot(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t rev = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<nplex::msgs::Update>>> updates = 0) {
  SnapshotBuilder builder_(_fbb);
  builder_.add_rev(rev);
  builder_.add_updates(updates);
  return builder_.Finish();
}

struct Snapshot::Traits {
  using type = Snapshot;
  static auto constexpr Create = CreateSnapshot;
};

inline ::flatbuffers::Offset<Snapshot> CreateSnapshotDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t rev = 0,
    const std::vector<::flatbuffers::Offset<nplex::msgs::Update>> *updates = nullptr) {
  auto updates__ = updates ? _fbb.CreateVector<::flatbuffers::Offset<nplex::msgs::Update>>(*updates) : 0;
  return nplex::msgs::CreateSnapshot(
      _fbb,
      rev,
      updates__);
}

struct Acl FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AclBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PATTERN = 4,
    VT_MODE = 6
  };
  const ::flatbuffers::String *pattern() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PATTERN);
  }
  uint8_t mode() const {
    return GetField<uint8_t>(VT_MODE, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_PATTERN) &&
           verifier.VerifyString(pattern()) &&
           VerifyField<uint8_t>(verifier, VT_MODE, 1) &&
           verifier.EndTable();
  }
};

struct AclBuilder {
  typedef Acl Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_pattern(::flatbuffers::Offset<::flatbuffers::String> pattern) {
    fbb_.AddOffset(Acl::VT_PATTERN, pattern);
  }
  void add_mode(uint8_t mode) {
    fbb_.AddElement<uint8_t>(Acl::VT_MODE, mode, 0);
  }
  explicit AclBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Acl> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Acl>(end);
    fbb_.Required(o, Acl::VT_PATTERN);
    return o;
  }
};

inline ::flatbuffers::Offset<Acl> CreateAcl(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> pattern = 0,
    uint8_t mode = 0) {
  AclBuilder builder_(_fbb);
  builder_.add_pattern(pattern);
  builder_.add_mode(mode);
  return builder_.Finish();
}

struct Acl::Traits {
  using type = Acl;
  static auto constexpr Create = CreateAcl;
};

inline ::flatbuffers::Offset<Acl> CreateAclDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *pattern = nullptr,
    uint8_t mode = 0) {
  auto pattern__ = pattern ? _fbb.CreateString(pattern) : 0;
  return nplex::msgs::CreateAcl(
      _fbb,
      pattern__,
      mode);
}

struct LoginRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LoginRequestBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CID = 4,
    VT_API_VERSION = 6,
    VT_USER = 8,
    VT_PASSWORD = 10
  };
  uint64_t cid() const {
    return GetField<uint64_t>(VT_CID, 0);
  }
  uint32_t api_version() const {
    return GetField<uint32_t>(VT_API_VERSION, 0);
  }
  const ::flatbuffers::String *user() const {
    return GetPointer<const ::flatbuffers::String *>(VT_USER);
  }
  const ::flatbuffers::String *password() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PASSWORD);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CID, 8) &&
           VerifyField<uint32_t>(verifier, VT_API_VERSION, 4) &&
           VerifyOffsetRequired(verifier, VT_USER) &&
           verifier.VerifyString(user()) &&
           VerifyOffsetRequired(verifier, VT_PASSWORD) &&
           verifier.VerifyString(password()) &&
           verifier.EndTable();
  }
};

struct LoginRequestBuilder {
  typedef LoginRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cid(uint64_t cid) {
    fbb_.AddElement<uint64_t>(LoginRequest::VT_CID, cid, 0);
  }
  void add_api_version(uint32_t api_version) {
    fbb_.AddElement<uint32_t>(LoginRequest::VT_API_VERSION, api_version, 0);
  }
  void add_user(::flatbuffers::Offset<::flatbuffers::String> user) {
    fbb_.AddOffset(LoginRequest::VT_USER, user);
  }
  void add_password(::flatbuffers::Offset<::flatbuffers::String> password) {
    fbb_.AddOffset(LoginRequest::VT_PASSWORD, password);
  }
  explicit LoginRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LoginRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LoginRequest>(end);
    fbb_.Required(o, LoginRequest::VT_USER);
    fbb_.Required(o, LoginRequest::VT_PASSWORD);
    return o;
  }
};

inline ::flatbuffers::Offset<LoginRequest> CreateLoginRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t cid = 0,
    uint32_t api_version = 0,
    ::flatbuffers::Offset<::flatbuffers::String> user = 0,
    ::flatbuffers::Offset<::flatbuffers::String> password = 0) {
  LoginRequestBuilder builder_(_fbb);
  builder_.add_cid(cid);
  builder_.add_password(password);
  builder_.add_user(user);
  builder_.add_api_version(api_version);
  return builder_.Finish();
}

struct LoginRequest::Traits {
  using type = LoginRequest;
  static auto constexpr Create = CreateLoginRequest;
};

inline ::flatbuffers::Offset<LoginRequest> CreateLoginRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t cid = 0,
    uint32_t api_version = 0,
    const char *user = nullptr,
    const char *password = nullptr) {
  auto user__ = user ? _fbb.CreateString(user) : 0;
  auto password__ = password ? _fbb.CreateString(password) : 0;
  return nplex::msgs::CreateLoginRequest(
      _fbb,
      cid,
      api_version,
      user__,
      password__);
}

struct LoginResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LoginResponseBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CID = 4,
    VT_CODE = 6,
    VT_REV0 = 8,
    VT_CREV = 10,
    VT_CAN_FORCE = 12,
    VT_KEEPALIVE = 14,
    VT_PERMISSIONS = 16
  };
  uint64_t cid() const {
    return GetField<uint64_t>(VT_CID, 0);
  }
  nplex::msgs::LoginCode code() const {
    return static_cast<nplex::msgs::LoginCode>(GetField<int8_t>(VT_CODE, 0));
  }
  uint64_t rev0() const {
    return GetField<uint64_t>(VT_REV0, 0);
  }
  uint64_t crev() const {
    return GetField<uint64_t>(VT_CREV, 0);
  }
  bool can_force() const {
    return GetField<uint8_t>(VT_CAN_FORCE, 0) != 0;
  }
  uint32_t keepalive() const {
    return GetField<uint32_t>(VT_KEEPALIVE, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<nplex::msgs::Acl>> *permissions() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<nplex::msgs::Acl>> *>(VT_PERMISSIONS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CID, 8) &&
           VerifyField<int8_t>(verifier, VT_CODE, 1) &&
           VerifyField<uint64_t>(verifier, VT_REV0, 8) &&
           VerifyField<uint64_t>(verifier, VT_CREV, 8) &&
           VerifyField<uint8_t>(verifier, VT_CAN_FORCE, 1) &&
           VerifyField<uint32_t>(verifier, VT_KEEPALIVE, 4) &&
           VerifyOffset(verifier, VT_PERMISSIONS) &&
           verifier.VerifyVector(permissions()) &&
           verifier.VerifyVectorOfTables(permissions()) &&
           verifier.EndTable();
  }
};

struct LoginResponseBuilder {
  typedef LoginResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cid(uint64_t cid) {
    fbb_.AddElement<uint64_t>(LoginResponse::VT_CID, cid, 0);
  }
  void add_code(nplex::msgs::LoginCode code) {
    fbb_.AddElement<int8_t>(LoginResponse::VT_CODE, static_cast<int8_t>(code), 0);
  }
  void add_rev0(uint64_t rev0) {
    fbb_.AddElement<uint64_t>(LoginResponse::VT_REV0, rev0, 0);
  }
  void add_crev(uint64_t crev) {
    fbb_.AddElement<uint64_t>(LoginResponse::VT_CREV, crev, 0);
  }
  void add_can_force(bool can_force) {
    fbb_.AddElement<uint8_t>(LoginResponse::VT_CAN_FORCE, static_cast<uint8_t>(can_force), 0);
  }
  void add_keepalive(uint32_t keepalive) {
    fbb_.AddElement<uint32_t>(LoginResponse::VT_KEEPALIVE, keepalive, 0);
  }
  void add_permissions(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<nplex::msgs::Acl>>> permissions) {
    fbb_.AddOffset(LoginResponse::VT_PERMISSIONS, permissions);
  }
  explicit LoginResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LoginResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LoginResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LoginResponse> CreateLoginResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t cid = 0,
    nplex::msgs::LoginCode code = nplex::msgs::LoginCode::AUTHORIZED,
    uint64_t rev0 = 0,
    uint64_t crev = 0,
    bool can_force = false,
    uint32_t keepalive = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<nplex::msgs::Acl>>> permissions = 0) {
  LoginResponseBuilder builder_(_fbb);
  builder_.add_crev(crev);
  builder_.add_rev0(rev0);
  builder_.add_cid(cid);
  builder_.add_permissions(permissions);
  builder_.add_keepalive(keepalive);
  builder_.add_can_force(can_force);
  builder_.add_code(code);
  return builder_.Finish();
}

struct LoginResponse::Traits {
  using type = LoginResponse;
  static auto constexpr Create = CreateLoginResponse;
};

inline ::flatbuffers::Offset<LoginResponse> CreateLoginResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t cid = 0,
    nplex::msgs::LoginCode code = nplex::msgs::LoginCode::AUTHORIZED,
    uint64_t rev0 = 0,
    uint64_t crev = 0,
    bool can_force = false,
    uint32_t keepalive = 0,
    const std::vector<::flatbuffers::Offset<nplex::msgs::Acl>> *permissions = nullptr) {
  auto permissions__ = permissions ? _fbb.CreateVector<::flatbuffers::Offset<nplex::msgs::Acl>>(*permissions) : 0;
  return nplex::msgs::CreateLoginResponse(
      _fbb,
      cid,
      code,
      rev0,
      crev,
      can_force,
      keepalive,
      permissions__);
}

struct PingRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PingRequestBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CID = 4,
    VT_PAYLOAD = 6
  };
  uint64_t cid() const {
    return GetField<uint64_t>(VT_CID, 0);
  }
  const ::flatbuffers::String *payload() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PAYLOAD);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CID, 8) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           verifier.VerifyString(payload()) &&
           verifier.EndTable();
  }
};

struct PingRequestBuilder {
  typedef PingRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cid(uint64_t cid) {
    fbb_.AddElement<uint64_t>(PingRequest::VT_CID, cid, 0);
  }
  void add_payload(::flatbuffers::Offset<::flatbuffers::String> payload) {
    fbb_.AddOffset(PingRequest::VT_PAYLOAD, payload);
  }
  explicit PingRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PingRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PingRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PingRequest> CreatePingRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t cid = 0,
    ::flatbuffers::Offset<::flatbuffers::String> payload = 0) {
  PingRequestBuilder builder_(_fbb);
  builder_.add_cid(cid);
  builder_.add_payload(payload);
  return builder_.Finish();
}

struct PingRequest::Traits {
  using type = PingRequest;
  static auto constexpr Create = CreatePingRequest;
};

inline ::flatbuffers::Offset<PingRequest> CreatePingRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t cid = 0,
    const char *payload = nullptr) {
  auto payload__ = payload ? _fbb.CreateString(payload) : 0;
  return nplex::msgs::CreatePingRequest(
      _fbb,
      cid,
      payload__);
}

struct PingResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PingResponseBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CID = 4,
    VT_CREV = 6,
    VT_PAYLOAD = 8
  };
  uint64_t cid() const {
    return GetField<uint64_t>(VT_CID, 0);
  }
  uint64_t crev() const {
    return GetField<uint64_t>(VT_CREV, 0);
  }
  const ::flatbuffers::String *payload() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PAYLOAD);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CID, 8) &&
           VerifyField<uint64_t>(verifier, VT_CREV, 8) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           verifier.VerifyString(payload()) &&
           verifier.EndTable();
  }
};

struct PingResponseBuilder {
  typedef PingResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cid(uint64_t cid) {
    fbb_.AddElement<uint64_t>(PingResponse::VT_CID, cid, 0);
  }
  void add_crev(uint64_t crev) {
    fbb_.AddElement<uint64_t>(PingResponse::VT_CREV, crev, 0);
  }
  void add_payload(::flatbuffers::Offset<::flatbuffers::String> payload) {
    fbb_.AddOffset(PingResponse::VT_PAYLOAD, payload);
  }
  explicit PingResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PingResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PingResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PingResponse> CreatePingResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t cid = 0,
    uint64_t crev = 0,
    ::flatbuffers::Offset<::flatbuffers::String> payload = 0) {
  PingResponseBuilder builder_(_fbb);
  builder_.add_crev(crev);
  builder_.add_cid(cid);
  builder_.add_payload(payload);
  return builder_.Finish();
}

struct PingResponse::Traits {
  using type = PingResponse;
  static auto constexpr Create = CreatePingResponse;
};

inline ::flatbuffers::Offset<PingResponse> CreatePingResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t cid = 0,
    uint64_t crev = 0,
    const char *payload = nullptr) {
  auto payload__ = payload ? _fbb.CreateString(payload) : 0;
  return nplex::msgs::CreatePingResponse(
      _fbb,
      cid,
      crev,
      payload__);
}

struct LoadRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LoadRequestBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CID = 4,
    VT_MODE = 6,
    VT_REV = 8
  };
  uint64_t cid() const {
    return GetField<uint64_t>(VT_CID, 0);
  }
  nplex::msgs::LoadMode mode() const {
    return static_cast<nplex::msgs::LoadMode>(GetField<int8_t>(VT_MODE, 0));
  }
  uint64_t rev() const {
    return GetField<uint64_t>(VT_REV, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CID, 8) &&
           VerifyField<int8_t>(verifier, VT_MODE, 1) &&
           VerifyField<uint64_t>(verifier, VT_REV, 8) &&
           verifier.EndTable();
  }
};

struct LoadRequestBuilder {
  typedef LoadRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cid(uint64_t cid) {
    fbb_.AddElement<uint64_t>(LoadRequest::VT_CID, cid, 0);
  }
  void add_mode(nplex::msgs::LoadMode mode) {
    fbb_.AddElement<int8_t>(LoadRequest::VT_MODE, static_cast<int8_t>(mode), 0);
  }
  void add_rev(uint64_t rev) {
    fbb_.AddElement<uint64_t>(LoadRequest::VT_REV, rev, 0);
  }
  explicit LoadRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LoadRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LoadRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LoadRequest> CreateLoadRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t cid = 0,
    nplex::msgs::LoadMode mode = nplex::msgs::LoadMode::SNAPSHOT_AT_LAST_REV,
    uint64_t rev = 0) {
  LoadRequestBuilder builder_(_fbb);
  builder_.add_rev(rev);
  builder_.add_cid(cid);
  builder_.add_mode(mode);
  return builder_.Finish();
}

struct LoadRequest::Traits {
  using type = LoadRequest;
  static auto constexpr Create = CreateLoadRequest;
};

struct LoadResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LoadResponseBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CID = 4,
    VT_CREV = 6,
    VT_ACCEPTED = 8,
    VT_SNAPSHOT = 10
  };
  uint64_t cid() const {
    return GetField<uint64_t>(VT_CID, 0);
  }
  uint64_t crev() const {
    return GetField<uint64_t>(VT_CREV, 0);
  }
  bool accepted() const {
    return GetField<uint8_t>(VT_ACCEPTED, 0) != 0;
  }
  const nplex::msgs::Snapshot *snapshot() const {
    return GetPointer<const nplex::msgs::Snapshot *>(VT_SNAPSHOT);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CID, 8) &&
           VerifyField<uint64_t>(verifier, VT_CREV, 8) &&
           VerifyField<uint8_t>(verifier, VT_ACCEPTED, 1) &&
           VerifyOffset(verifier, VT_SNAPSHOT) &&
           verifier.VerifyTable(snapshot()) &&
           verifier.EndTable();
  }
};

struct LoadResponseBuilder {
  typedef LoadResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cid(uint64_t cid) {
    fbb_.AddElement<uint64_t>(LoadResponse::VT_CID, cid, 0);
  }
  void add_crev(uint64_t crev) {
    fbb_.AddElement<uint64_t>(LoadResponse::VT_CREV, crev, 0);
  }
  void add_accepted(bool accepted) {
    fbb_.AddElement<uint8_t>(LoadResponse::VT_ACCEPTED, static_cast<uint8_t>(accepted), 0);
  }
  void add_snapshot(::flatbuffers::Offset<nplex::msgs::Snapshot> snapshot) {
    fbb_.AddOffset(LoadResponse::VT_SNAPSHOT, snapshot);
  }
  explicit LoadResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LoadResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LoadResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LoadResponse> CreateLoadResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t cid = 0,
    uint64_t crev = 0,
    bool accepted = false,
    ::flatbuffers::Offset<nplex::msgs::Snapshot> snapshot = 0) {
  LoadResponseBuilder builder_(_fbb);
  builder_.add_crev(crev);
  builder_.add_cid(cid);
  builder_.add_snapshot(snapshot);
  builder_.add_accepted(accepted);
  return builder_.Finish();
}

struct LoadResponse::Traits {
  using type = LoadResponse;
  static auto constexpr Create = CreateLoadResponse;
};

struct ChangesPush FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ChangesPushBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CID = 4,
    VT_CREV = 6,
    VT_UPDATES = 8
  };
  uint64_t cid() const {
    return GetField<uint64_t>(VT_CID, 0);
  }
  uint64_t crev() const {
    return GetField<uint64_t>(VT_CREV, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<nplex::msgs::Update>> *updates() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<nplex::msgs::Update>> *>(VT_UPDATES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CID, 8) &&
           VerifyField<uint64_t>(verifier, VT_CREV, 8) &&
           VerifyOffset(verifier, VT_UPDATES) &&
           verifier.VerifyVector(updates()) &&
           verifier.VerifyVectorOfTables(updates()) &&
           verifier.EndTable();
  }
};

struct ChangesPushBuilder {
  typedef ChangesPush Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cid(uint64_t cid) {
    fbb_.AddElement<uint64_t>(ChangesPush::VT_CID, cid, 0);
  }
  void add_crev(uint64_t crev) {
    fbb_.AddElement<uint64_t>(ChangesPush::VT_CREV, crev, 0);
  }
  void add_updates(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<nplex::msgs::Update>>> updates) {
    fbb_.AddOffset(ChangesPush::VT_UPDATES, updates);
  }
  explicit ChangesPushBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ChangesPush> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ChangesPush>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ChangesPush> CreateChangesPush(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t cid = 0,
    uint64_t crev = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<nplex::msgs::Update>>> updates = 0) {
  ChangesPushBuilder builder_(_fbb);
  builder_.add_crev(crev);
  builder_.add_cid(cid);
  builder_.add_updates(updates);
  return builder_.Finish();
}

struct ChangesPush::Traits {
  using type = ChangesPush;
  static auto constexpr Create = CreateChangesPush;
};

inline ::flatbuffers::Offset<ChangesPush> CreateChangesPushDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t cid = 0,
    uint64_t crev = 0,
    const std::vector<::flatbuffers::Offset<nplex::msgs::Update>> *updates = nullptr) {
  auto updates__ = updates ? _fbb.CreateVector<::flatbuffers::Offset<nplex::msgs::Update>>(*updates) : 0;
  return nplex::msgs::CreateChangesPush(
      _fbb,
      cid,
      crev,
      updates__);
}

struct SubmitRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SubmitRequestBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CID = 4,
    VT_CREV = 6,
    VT_TYPE = 8,
    VT_UPSERTS = 10,
    VT_DELETES = 12,
    VT_ENSURES = 14,
    VT_FORCE = 16
  };
  uint64_t cid() const {
    return GetField<uint64_t>(VT_CID, 0);
  }
  uint64_t crev() const {
    return GetField<uint64_t>(VT_CREV, 0);
  }
  uint32_t type() const {
    return GetField<uint32_t>(VT_TYPE, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<nplex::msgs::KeyValue>> *upserts() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<nplex::msgs::KeyValue>> *>(VT_UPSERTS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *deletes() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_DELETES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *ensures() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_ENSURES);
  }
  bool force() const {
    return GetField<uint8_t>(VT_FORCE, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CID, 8) &&
           VerifyField<uint64_t>(verifier, VT_CREV, 8) &&
           VerifyField<uint32_t>(verifier, VT_TYPE, 4) &&
           VerifyOffset(verifier, VT_UPSERTS) &&
           verifier.VerifyVector(upserts()) &&
           verifier.VerifyVectorOfTables(upserts()) &&
           VerifyOffset(verifier, VT_DELETES) &&
           verifier.VerifyVector(deletes()) &&
           verifier.VerifyVectorOfStrings(deletes()) &&
           VerifyOffset(verifier, VT_ENSURES) &&
           verifier.VerifyVector(ensures()) &&
           verifier.VerifyVectorOfStrings(ensures()) &&
           VerifyField<uint8_t>(verifier, VT_FORCE, 1) &&
           verifier.EndTable();
  }
};

struct SubmitRequestBuilder {
  typedef SubmitRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cid(uint64_t cid) {
    fbb_.AddElement<uint64_t>(SubmitRequest::VT_CID, cid, 0);
  }
  void add_crev(uint64_t crev) {
    fbb_.AddElement<uint64_t>(SubmitRequest::VT_CREV, crev, 0);
  }
  void add_type(uint32_t type) {
    fbb_.AddElement<uint32_t>(SubmitRequest::VT_TYPE, type, 0);
  }
  void add_upserts(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<nplex::msgs::KeyValue>>> upserts) {
    fbb_.AddOffset(SubmitRequest::VT_UPSERTS, upserts);
  }
  void add_deletes(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> deletes) {
    fbb_.AddOffset(SubmitRequest::VT_DELETES, deletes);
  }
  void add_ensures(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> ensures) {
    fbb_.AddOffset(SubmitRequest::VT_ENSURES, ensures);
  }
  void add_force(bool force) {
    fbb_.AddElement<uint8_t>(SubmitRequest::VT_FORCE, static_cast<uint8_t>(force), 0);
  }
  explicit SubmitRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SubmitRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SubmitRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SubmitRequest> CreateSubmitRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t cid = 0,
    uint64_t crev = 0,
    uint32_t type = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<nplex::msgs::KeyValue>>> upserts = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> deletes = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> ensures = 0,
    bool force = false) {
  SubmitRequestBuilder builder_(_fbb);
  builder_.add_crev(crev);
  builder_.add_cid(cid);
  builder_.add_ensures(ensures);
  builder_.add_deletes(deletes);
  builder_.add_upserts(upserts);
  builder_.add_type(type);
  builder_.add_force(force);
  return builder_.Finish();
}

struct SubmitRequest::Traits {
  using type = SubmitRequest;
  static auto constexpr Create = CreateSubmitRequest;
};

inline ::flatbuffers::Offset<SubmitRequest> CreateSubmitRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t cid = 0,
    uint64_t crev = 0,
    uint32_t type = 0,
    const std::vector<::flatbuffers::Offset<nplex::msgs::KeyValue>> *upserts = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *deletes = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *ensures = nullptr,
    bool force = false) {
  auto upserts__ = upserts ? _fbb.CreateVector<::flatbuffers::Offset<nplex::msgs::KeyValue>>(*upserts) : 0;
  auto deletes__ = deletes ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*deletes) : 0;
  auto ensures__ = ensures ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*ensures) : 0;
  return nplex::msgs::CreateSubmitRequest(
      _fbb,
      cid,
      crev,
      type,
      upserts__,
      deletes__,
      ensures__,
      force);
}

struct SubmitResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SubmitResponseBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CID = 4,
    VT_CREV = 6,
    VT_CODE = 8,
    VT_EREV = 10
  };
  uint64_t cid() const {
    return GetField<uint64_t>(VT_CID, 0);
  }
  uint64_t crev() const {
    return GetField<uint64_t>(VT_CREV, 0);
  }
  nplex::msgs::SubmitCode code() const {
    return static_cast<nplex::msgs::SubmitCode>(GetField<int8_t>(VT_CODE, 0));
  }
  uint64_t erev() const {
    return GetField<uint64_t>(VT_EREV, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CID, 8) &&
           VerifyField<uint64_t>(verifier, VT_CREV, 8) &&
           VerifyField<int8_t>(verifier, VT_CODE, 1) &&
           VerifyField<uint64_t>(verifier, VT_EREV, 8) &&
           verifier.EndTable();
  }
};

struct SubmitResponseBuilder {
  typedef SubmitResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cid(uint64_t cid) {
    fbb_.AddElement<uint64_t>(SubmitResponse::VT_CID, cid, 0);
  }
  void add_crev(uint64_t crev) {
    fbb_.AddElement<uint64_t>(SubmitResponse::VT_CREV, crev, 0);
  }
  void add_code(nplex::msgs::SubmitCode code) {
    fbb_.AddElement<int8_t>(SubmitResponse::VT_CODE, static_cast<int8_t>(code), 0);
  }
  void add_erev(uint64_t erev) {
    fbb_.AddElement<uint64_t>(SubmitResponse::VT_EREV, erev, 0);
  }
  explicit SubmitResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SubmitResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SubmitResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SubmitResponse> CreateSubmitResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t cid = 0,
    uint64_t crev = 0,
    nplex::msgs::SubmitCode code = nplex::msgs::SubmitCode::ACCEPTED,
    uint64_t erev = 0) {
  SubmitResponseBuilder builder_(_fbb);
  builder_.add_erev(erev);
  builder_.add_crev(crev);
  builder_.add_cid(cid);
  builder_.add_code(code);
  return builder_.Finish();
}

struct SubmitResponse::Traits {
  using type = SubmitResponse;
  static auto constexpr Create = CreateSubmitResponse;
};

struct KeepAlivePush FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef KeepAlivePushBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CREV = 4
  };
  uint64_t crev() const {
    return GetField<uint64_t>(VT_CREV, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CREV, 8) &&
           verifier.EndTable();
  }
};

struct KeepAlivePushBuilder {
  typedef KeepAlivePush Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_crev(uint64_t crev) {
    fbb_.AddElement<uint64_t>(KeepAlivePush::VT_CREV, crev, 0);
  }
  explicit KeepAlivePushBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<KeepAlivePush> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<KeepAlivePush>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<KeepAlivePush> CreateKeepAlivePush(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t crev = 0) {
  KeepAlivePushBuilder builder_(_fbb);
  builder_.add_crev(crev);
  return builder_.Finish();
}

struct KeepAlivePush::Traits {
  using type = KeepAlivePush;
  static auto constexpr Create = CreateKeepAlivePush;
};

struct Message FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MessageBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CONTENT_TYPE = 4,
    VT_CONTENT = 6
  };
  nplex::msgs::MsgContent content_type() const {
    return static_cast<nplex::msgs::MsgContent>(GetField<uint8_t>(VT_CONTENT_TYPE, 0));
  }
  const void *content() const {
    return GetPointer<const void *>(VT_CONTENT);
  }
  template<typename T> const T *content_as() const;
  const nplex::msgs::PingRequest *content_as_PING_REQUEST() const {
    return content_type() == nplex::msgs::MsgContent::PING_REQUEST ? static_cast<const nplex::msgs::PingRequest *>(content()) : nullptr;
  }
  const nplex::msgs::PingResponse *content_as_PING_RESPONSE() const {
    return content_type() == nplex::msgs::MsgContent::PING_RESPONSE ? static_cast<const nplex::msgs::PingResponse *>(content()) : nullptr;
  }
  const nplex::msgs::LoginRequest *content_as_LOGIN_REQUEST() const {
    return content_type() == nplex::msgs::MsgContent::LOGIN_REQUEST ? static_cast<const nplex::msgs::LoginRequest *>(content()) : nullptr;
  }
  const nplex::msgs::LoginResponse *content_as_LOGIN_RESPONSE() const {
    return content_type() == nplex::msgs::MsgContent::LOGIN_RESPONSE ? static_cast<const nplex::msgs::LoginResponse *>(content()) : nullptr;
  }
  const nplex::msgs::LoadRequest *content_as_LOAD_REQUEST() const {
    return content_type() == nplex::msgs::MsgContent::LOAD_REQUEST ? static_cast<const nplex::msgs::LoadRequest *>(content()) : nullptr;
  }
  const nplex::msgs::LoadResponse *content_as_LOAD_RESPONSE() const {
    return content_type() == nplex::msgs::MsgContent::LOAD_RESPONSE ? static_cast<const nplex::msgs::LoadResponse *>(content()) : nullptr;
  }
  const nplex::msgs::SubmitRequest *content_as_SUBMIT_REQUEST() const {
    return content_type() == nplex::msgs::MsgContent::SUBMIT_REQUEST ? static_cast<const nplex::msgs::SubmitRequest *>(content()) : nullptr;
  }
  const nplex::msgs::SubmitResponse *content_as_SUBMIT_RESPONSE() const {
    return content_type() == nplex::msgs::MsgContent::SUBMIT_RESPONSE ? static_cast<const nplex::msgs::SubmitResponse *>(content()) : nullptr;
  }
  const nplex::msgs::ChangesPush *content_as_CHANGES_PUSH() const {
    return content_type() == nplex::msgs::MsgContent::CHANGES_PUSH ? static_cast<const nplex::msgs::ChangesPush *>(content()) : nullptr;
  }
  const nplex::msgs::KeepAlivePush *content_as_KEEPALIVE_PUSH() const {
    return content_type() == nplex::msgs::MsgContent::KEEPALIVE_PUSH ? static_cast<const nplex::msgs::KeepAlivePush *>(content()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_CONTENT_TYPE, 1) &&
           VerifyOffset(verifier, VT_CONTENT) &&
           VerifyMsgContent(verifier, content(), content_type()) &&
           verifier.EndTable();
  }
};

template<> inline const nplex::msgs::PingRequest *Message::content_as<nplex::msgs::PingRequest>() const {
  return content_as_PING_REQUEST();
}

template<> inline const nplex::msgs::PingResponse *Message::content_as<nplex::msgs::PingResponse>() const {
  return content_as_PING_RESPONSE();
}

template<> inline const nplex::msgs::LoginRequest *Message::content_as<nplex::msgs::LoginRequest>() const {
  return content_as_LOGIN_REQUEST();
}

template<> inline const nplex::msgs::LoginResponse *Message::content_as<nplex::msgs::LoginResponse>() const {
  return content_as_LOGIN_RESPONSE();
}

template<> inline const nplex::msgs::LoadRequest *Message::content_as<nplex::msgs::LoadRequest>() const {
  return content_as_LOAD_REQUEST();
}

template<> inline const nplex::msgs::LoadResponse *Message::content_as<nplex::msgs::LoadResponse>() const {
  return content_as_LOAD_RESPONSE();
}

template<> inline const nplex::msgs::SubmitRequest *Message::content_as<nplex::msgs::SubmitRequest>() const {
  return content_as_SUBMIT_REQUEST();
}

template<> inline const nplex::msgs::SubmitResponse *Message::content_as<nplex::msgs::SubmitResponse>() const {
  return content_as_SUBMIT_RESPONSE();
}

template<> inline const nplex::msgs::ChangesPush *Message::content_as<nplex::msgs::ChangesPush>() const {
  return content_as_CHANGES_PUSH();
}

template<> inline const nplex::msgs::KeepAlivePush *Message::content_as<nplex::msgs::KeepAlivePush>() const {
  return content_as_KEEPALIVE_PUSH();
}

struct MessageBuilder {
  typedef Message Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_content_type(nplex::msgs::MsgContent content_type) {
    fbb_.AddElement<uint8_t>(Message::VT_CONTENT_TYPE, static_cast<uint8_t>(content_type), 0);
  }
  void add_content(::flatbuffers::Offset<void> content) {
    fbb_.AddOffset(Message::VT_CONTENT, content);
  }
  explicit MessageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Message> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Message>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Message> CreateMessage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    nplex::msgs::MsgContent content_type = nplex::msgs::MsgContent::NONE,
    ::flatbuffers::Offset<void> content = 0) {
  MessageBuilder builder_(_fbb);
  builder_.add_content(content);
  builder_.add_content_type(content_type);
  return builder_.Finish();
}

struct Message::Traits {
  using type = Message;
  static auto constexpr Create = CreateMessage;
};

inline bool VerifyMsgContent(::flatbuffers::Verifier &verifier, const void *obj, MsgContent type) {
  switch (type) {
    case MsgContent::NONE: {
      return true;
    }
    case MsgContent::PING_REQUEST: {
      auto ptr = reinterpret_cast<const nplex::msgs::PingRequest *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MsgContent::PING_RESPONSE: {
      auto ptr = reinterpret_cast<const nplex::msgs::PingResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MsgContent::LOGIN_REQUEST: {
      auto ptr = reinterpret_cast<const nplex::msgs::LoginRequest *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MsgContent::LOGIN_RESPONSE: {
      auto ptr = reinterpret_cast<const nplex::msgs::LoginResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MsgContent::LOAD_REQUEST: {
      auto ptr = reinterpret_cast<const nplex::msgs::LoadRequest *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MsgContent::LOAD_RESPONSE: {
      auto ptr = reinterpret_cast<const nplex::msgs::LoadResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MsgContent::SUBMIT_REQUEST: {
      auto ptr = reinterpret_cast<const nplex::msgs::SubmitRequest *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MsgContent::SUBMIT_RESPONSE: {
      auto ptr = reinterpret_cast<const nplex::msgs::SubmitResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MsgContent::CHANGES_PUSH: {
      auto ptr = reinterpret_cast<const nplex::msgs::ChangesPush *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MsgContent::KEEPALIVE_PUSH: {
      auto ptr = reinterpret_cast<const nplex::msgs::KeepAlivePush *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyMsgContentVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<MsgContent> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyMsgContent(
        verifier,  values->Get(i), types->GetEnum<MsgContent>(i))) {
      return false;
    }
  }
  return true;
}

inline const nplex::msgs::Message *GetMessage(const void *buf) {
  return ::flatbuffers::GetRoot<nplex::msgs::Message>(buf);
}

inline const nplex::msgs::Message *GetSizePrefixedMessage(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<nplex::msgs::Message>(buf);
}

inline bool VerifyMessageBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<nplex::msgs::Message>(nullptr);
}

inline bool VerifySizePrefixedMessageBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<nplex::msgs::Message>(nullptr);
}

inline void FinishMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<nplex::msgs::Message> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<nplex::msgs::Message> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace msgs
}  // namespace nplex

#endif  // FLATBUFFERS_GENERATED_MESSAGES_NPLEX_MSGS_H_
